version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:latest
    container_name: trainmaster-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trainmaster
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trainmaster-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da aplicação TrainMaster
  trainmaster-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainmaster-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./logs:/app/logs
    networks:
      - trainmaster-network

networks:
  trainmaster-network:
    driver: bridge

volumes:
  postgres-data:
